package com.frame.base.model;

/**
 * User generated by hbm2java
 */
public class Org{

	private String id;
	private String name;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
