package com.frame.base.model;

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User {

	private String id;			//编号
	private String userTypeid;	//用户组
	private String name;		//姓名
	private String alias;		//昵称，别名
	private String password;	//密码
	private String sex;			//性别,0-男，1-女
	private String idNumber;	//身份证号
	private Date birthday;		//出生日期
	private String tel;			//电话
	private String fax;			//传真	
	private String email;		//邮箱
	private String qq;			//QQ
	private String address;		//地址
	private Date registerTime;	//用户注册系统时间
	private Date expireTime;	//用户注销账号时间
	private Date loginTime;		//用户最近登录时间
	private String loginIp;		//用户最近登录IP
	private String flagActive;	//用户是否激活,1-是，0-否
	private String flagApproved;//用户是否得到系统许可发布信息，1-是，0-否
	private String remark;		//备注

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserTypeid() {
		return this.userTypeid;
	}

	public void setUserTypeid(String userTypeid) {
		this.userTypeid = userTypeid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public String getFlagActive() {
		return flagActive;
	}

	public void setFlagActive(String flagActive) {
		this.flagActive = flagActive;
	}

	public String getFlagApproved() {
		return flagApproved;
	}

	public void setFlagApproved(String flagApproved) {
		this.flagApproved = flagApproved;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
